### ISSUE TITLE
It is too easy to progress in the game

### ISSUE THREAD

**Issue by mcthouacbb** [JerryCourtroom/Shoe-Clicker#2]
![image](https://github.com/JerryCourtroom/Shoe-Clicker/assets/38298419/eeb71fcd-8c32-4eed-8bd5-d2048743b878)
As you can see here, I have reached infinity shoes in a relatively short time period. Currently, it is too easy to progress very far into the game, as the growth of the shoes is exponential. The shoes per click upgrade is too strong, and needs to be nerfed to be subexponential so that progression is not so quick.

**Comment by JerryCourtroom** [comment]
The Shoes per Click upgrade cost now increases quadratically, but the Shoes per Click for each upgrade increases linearly. I'll close this issue for now, but please let me know if the progression is still too quick.

**Comment by JerryCourtroom** [comment]
I planned it out so, assuming you don't purchase the lucky ring, it takes 5 minutes at first to upgrade Shoes per Click, then 10 minutes, then 15, etc.

**Comment by JerryCourtroom** [comment]
That plan is also assuming that the user clicks on an average of 5 clicks per second.
